const express=require('express');const db=require('../db');const {normalizePersian}=require('../lib/persian');const {money,resolveAccount,postVoucher,deleteSourceVoucher,assertPeriodOpen,recomputeBankBalances}=require('../lib/accounting');const router=express.Router();
function settings(){return db.prepare('SELECT * FROM accounting_settings WHERE id=1').get()||{};}
function partyAccount(row){const p=db.prepare('SELECT legal_status FROM parties WHERE name_normalized=?').get(normalizePersian(row.party));return p?.legal_status==='individual'?(row.type==='received'?'1412':'3202'):(row.type==='received'?'1411':'3201');}
function post(row){const s=settings();const party=resolveAccount(null,partyAccount(row),'حساب طرف حساب');const cheque=row.type==='received'?resolveAccount(s.cheque_receivable_account_id,'1403','اسناد دریافتنی'):resolveAccount(s.cheque_payable_account_id,'3101','اسناد پرداختنی');let bank=null;if(row.bank_account_id) bank=db.prepare('SELECT coa_account_id FROM bank_accounts WHERE id=?').get(row.bank_account_id)?.coa_account_id;const desc=`چک ${row.type==='received'?'دریافتنی':'پرداختنی'} شماره ${row.id} — ${row.party}`;let lines;if(row.type==='received'){if(row.status==='وصول شده'){if(!bank)throw new Error('برای چک وصول‌شده حساب بانکی الزامی است.');lines=[{account_id:bank,debit:row.amount,credit:0},{account_id:party,debit:0,credit:row.amount}];}else if(row.status==='برگشتی'){lines=[{account_id:party,debit:row.amount,credit:0},{account_id:cheque,debit:0,credit:row.amount}];}else{lines=[{account_id:cheque,debit:row.amount,credit:0},{account_id:party,debit:0,credit:row.amount}];}}else{if(row.status==='پرداخت شده'){if(!bank)throw new Error('برای چک پرداخت‌شده حساب بانکی الزامی است.');lines=[{account_id:party,debit:row.amount,credit:0},{account_id:bank,debit:0,credit:row.amount}];}else if(row.status==='برگشتی'){lines=[{account_id:cheque,debit:row.amount,credit:0},{account_id:party,debit:0,credit:row.amount}];}else{lines=[{account_id:party,debit:row.amount,credit:0},{account_id:cheque,debit:0,credit:row.amount}];}}return postVoucher({date:row.due_date,description:desc,sourceType:'cheque',sourceId:row.id,lines});}
const get=id=>db.prepare('SELECT * FROM cheques WHERE id=?').get(id);
router.get('/',(req,res)=>res.json(db.prepare('SELECT c.*,b.name bank_account_name FROM cheques c LEFT JOIN bank_accounts b ON b.id=c.bank_account_id ORDER BY c.id DESC').all()));
router.post('/',(req,res)=>{try{const amount=money(req.body.amount,'مبلغ');if(amount<=0)throw new Error('مبلغ چک باید بیشتر از صفر باشد.');const {type,party,due_date,status='در جریان وصول',sayad_id='',endorsed_to='',bank_account_id=null}=req.body;if(!['received','issued'].includes(type)||!party||!due_date)throw new Error('اطلاعات چک نامعتبر است.');assertPeriodOpen(due_date);const tx=db.transaction(()=>{const info=db.prepare('INSERT INTO cheques(type,party,amount,due_date,status,sayad_id,endorsed_to,bank_account_id) VALUES(?,?,?,?,?,?,?,?)').run(type,party,amount,due_date,status,sayad_id,endorsed_to,bank_account_id);const id=Number(info.lastInsertRowid);post(get(id));recomputeBankBalances();return id;});res.status(201).json(get(tx()));}catch(e){res.status(400).json({error:e.message});}});
router.put('/:id',(req,res)=>{try{const old=get(req.params.id);if(!old)return res.status(404).json({error:'not found'});const amount=money(req.body.amount,'مبلغ');assertPeriodOpen(req.body.due_date);const tx=db.transaction(()=>{deleteSourceVoucher('cheque',old.id);db.prepare('UPDATE cheques SET type=?,party=?,amount=?,due_date=?,status=?,sayad_id=?,endorsed_to=?,bank_account_id=? WHERE id=?').run(req.body.type,req.body.party,amount,req.body.due_date,req.body.status,req.body.sayad_id||'',req.body.endorsed_to||'',req.body.bank_account_id||null,old.id);post(get(old.id));recomputeBankBalances();return old.id;});tx();res.json(get(old.id));}catch(e){res.status(400).json({error:e.message});}});
router.delete('/:id',(req,res)=>{try{const row=get(req.params.id);if(!row)return res.status(404).json({error:'not found'});assertPeriodOpen(row.due_date);const tx=db.transaction(()=>{deleteSourceVoucher('cheque',row.id);db.prepare('DELETE FROM cheques WHERE id=?').run(row.id);recomputeBankBalances();});tx();res.status(204).end();}catch(e){res.status(400).json({error:e.message});}});module.exports=router;
